stages:
  - build

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

.build:
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  stage: build
  script:
    - ./gradlew --warning-mode=all build
  cache:
    - key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
      paths:
        - .gradle/wrapper
    - key: $CI_COMMIT_REF_SLUG
      fallback_keys:
        - master-protected
      paths:
        - .gradle/caches
  artifacts:
    when: always
    paths:
      - build/test-results/
      - build/reports/jacoco/
    reports:
      junit: build/test-results/**/TEST-*.xml

build:java8:
  extends: .build
  image: eclipse-temurin:8-jdk

build:java11:
  extends: .build
  image: eclipse-temurin:11.0.28_6-jdk

build:java17:
  extends: .build
  image: eclipse-temurin:17.0.16_8-jdk
  script:
    - ./gradlew --warning-mode=all build jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3}) ?%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: build/reports/jacoco/**/*.xml

build:java21:
  extends: .build
  image: eclipse-temurin:21.0.8_9-jdk

build:java24:
  extends: .build
  image: eclipse-temurin:24-jdk
